(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Input::Initialization:: *)
<<SARAH.m


(* ::Input::Initialization:: *)
Start["THDM"]


(* ::Input::Initialization:: *)
mine=Intersection[Simplify[Abs[FullSimplify[Eigenvalues[Get2to2scattering /. conj[x_]->x]]]]];
mine=Sort[mine];


(* ::Input::Initialization:: *)
sub={L1->2 Lambda1,L2->2 Lambda2,L3->Lambda3,L4->Lambda4,L5->Lambda5};


(* ::Input::Initialization:: *)
ref={L3+L4,L3-L4,L3+L5,L3+2L4+3L5,L3-L5,L3+2L4-3L5,1/2(L1+L2) + 1/2 Sqrt[(L1-L2)^2+4 L5^2],1/2(L1+L2) - 1/2 Sqrt[(L1-L2)^2+4 L5^2],
1/2(L1+L2)+1/2 Sqrt[(L1-L2)^2+4 L4^2],1/2(L1+L2)-1/2 Sqrt[(L1-L2)^2+4 L4^2],3/2 (L1+L2)+Sqrt[9/4(L1-L2)^2+(2L3+L4)^2],3/2 (L1+L2)-Sqrt[9/4(L1-L2)^2+(2L3+L4)^2]}  ;


(* ::Input::Initialization:: *)
ref2=Abs/@ref /. sub;


(* ::Input::Initialization:: *)
diff=DeleteCases[FullSimplify[Sort[mine]-Sort[ref2] ],0]


(* ::Input::Initialization:: *)
out=OpenWrite["THDM_Unitarity_debug.txt"];
WriteString[out,ToString[Length[diff]]];
Close[out];
